"""Automatically generated by binding_generator.py.

MuJoCo header version: 150
"""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# pylint: disable=invalid-name

# ----------------------------------Constants----------------------------------

mjUSEDOUBLE = True
mjUSEAVX = True
mjMINVAL = 1e-15
mjPI = 3.141592653589793
mjMAXVAL = 10000000000.0
mjMINMU = 1e-05
mjMINIMP = 0.0001
mjMAXIMP = 0.9999
mjMAXCONPAIR = 50
mjMAXVFS = 200
mjMAXVFSNAME = 100
mjNEQDATA = 7
mjNDYN = 3
mjNGAIN = 3
mjNBIAS = 3
mjNREF = 2
mjNIMP = 3
mjNSOLVER = 1000
mjNGROUP = 5
mjMAXOVERLAY = 500
mjMAXLINE = 100
mjMAXLINEPNT = 500
mjMAXPLANEGRID = 100
MJAPI = True
mjVERSION_HEADER = 150

# ----------------------------End of generated code----------------------------
